/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primerapractica;

import javax.swing.table.DefaultTableModel;
import models.Apuesta.Apuesta;
import models.Apuesta.ApuestaBuilder;
import models.Apuesta.ApuestaMarcadorBuilder;
import models.Apuesta.ApuestaResultadoBuilder;
import models.Apuesta.DirectorApuesta;

/**
 *
 * @author Tito Jesús Yánac Saldaña
 * @codigo 10200176
 * @correo 1200176@unmsm.edu.pe
 * @curso Patrones de Diseño
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        field_nombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea_Resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Examen");

        jLabel2.setText("* Si tu apuesta es tipo 1, ingresa solamente score 1 para el equipo ganador.");

        jLabel4.setText("* Si tu apuesta es tipo 2,ingresa score de los equipos.");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Equipo 1", "Score", "", "Equipo 2", "Score", "Monto de Apuesta"
            }
        ));
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        jButton1.setText("Generar Encuentros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre:");

        jButton2.setText("Mostrar Resultado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TextArea_Resultado.setColumns(20);
        TextArea_Resultado.setRows(5);
        jScrollPane2.setViewportView(TextArea_Resultado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
               
        
        for (int i = 0; i < 10; i++) {
            String equipo1 = (String) modelo.getValueAt(i, 0);
            String scoreEquipo1 = (String) modelo.getValueAt(i, 1);
            String equipo2 = (String) modelo.getValueAt(i, 3); 
            String scoreEquipo2 = (String) modelo.getValueAt(i, 4);
            String monto = (String) modelo.getValueAt(i, 5);
            
            //valida que exista un encuentro y un monto
            if(!equipo1.equals("") && !equipo2.equals("") && !monto.equals("")){
                //valida el tipo de apuesta
                if( (scoreEquipo1.equals("") && scoreEquipo2.equals("")) ||
                    (scoreEquipo1.equals("") && scoreEquipo2.equals("1")) ||
                    (scoreEquipo1.equals("1") && scoreEquipo2.equals(""))){
                    //apuesta tipo1 -> a ganador
                    
                        DirectorApuesta da=new DirectorApuesta();
                        ApuestaBuilder xresultado=new ApuestaResultadoBuilder();
                        da.setApuestaBuilder(xresultado);
                        da.contruirApuesta();
                        Apuesta apuesta=da.getApuesta();
                        System.out.println(apuesta.getBonificacion() );
                        
                        String texto="\n--------------------------\n";
                        int ganador = (int) Math.floor(Math.random()*2); 
                        if(
                            (ganador == 0 && scoreEquipo1.equals("1"))||
                            (ganador == 1 && scoreEquipo2.equals("1"))
                        ){
                        
                            texto+= "\n#"+i+"\nFelicidades !!!!\n";
                            texto+= field_nombre.getText()+"\n";
                            texto+= "Se realizo apuesta x ganador\n";
                            texto+= "Monto apostado: "+ monto;
                            double bonificacion = apuesta.getBonificacion();
                            double total = Double.parseDouble(monto)*bonificacion;
                            texto+= "Premio: "+ total;
                            TextArea_Resultado.setText(texto);
                        }else{
                            texto+= "\n#"+i+"\n........Siguen Intentando......\n";
                            texto+= field_nombre.getText()+"\n";
                            texto+= "Se realizo apuesta x ganador\n";
                            texto+= "Monto apostado: "+ monto;
                            double bonificacion = apuesta.getBonificacion();
                            double total = Double.parseDouble(monto)*bonificacion;
                            texto+= "Premio: "+ total;
                            TextArea_Resultado.setText(texto);
                            
                        }
                        
                }else{
                    //apuesta tipo2 -> x score
                    
                        DirectorApuesta da=new DirectorApuesta();
                        ApuestaBuilder xScore=new ApuestaResultadoBuilder();
                        da.setApuestaBuilder(xScore);
                        da.contruirApuesta();
                        Apuesta apuesta=da.getApuesta();
                        System.out.println(apuesta.getBonificacion() );
                        
                        String texto="\n--------------------------\n";
                        int valor1 = (int) Math.floor(Math.random()*3); 
                        int valor2 = (int) Math.floor(Math.random()*3); 
                        int ganador;
                        if (valor2 > valor1)
                            ganador =1;
                        else if(valor1 > valor2)
                            ganador = 0;
                        else
                            ganador = 2;
                        if(
                                (ganador == 0 && scoreEquipo1.equals(valor1)) ||
                                (ganador == 1 && scoreEquipo2.equals(valor2)) ||
                                (ganador == 2 && scoreEquipo1.equals(valor1) && scoreEquipo2.equals(valor2))
                            )
                        texto+= field_nombre.getText()+"\n";
                        texto+= "\n#"+i+"\nSe realizo apuesta x ganador\n";
                        texto+= "Monto apostado: "+ monto;
                        texto+= "Prediccion: " + scoreEquipo1 + " - " + scoreEquipo2;
                        texto+= "Felicidades !!!!\n";
                        texto+= "Resultado: " + valor1 + " - " + valor2;
                        double bonificacion = apuesta.getBonificacion();
                        double total = Double.parseDouble(monto)*bonificacion;
                        texto+= "Premio: "+ total;
                        TextArea_Resultado.setText(texto);
                }
                
            }
            //si monto apuesta !=0 registrar apuesta
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        tabla.setValueAt("equipo 1", 0, 0);
        tabla.setValueAt("equipo 2", 1, 0);
        tabla.setValueAt("equipo 3", 2, 0);
        tabla.setValueAt("equipo 4", 3, 0);
        tabla.setValueAt("equipo 5", 4, 0);
        tabla.setValueAt("equipo 6", 5, 0);
        tabla.setValueAt("equipo 7", 6, 0);
        tabla.setValueAt("equipo 8", 7, 0);
        tabla.setValueAt("equipo 9", 8, 0);
        
        tabla.setValueAt("vs", 0, 2);
        tabla.setValueAt("vs", 1, 2);
        tabla.setValueAt("vs", 2, 2);
        tabla.setValueAt("vs", 3, 2);
        tabla.setValueAt("vs", 4, 2);
        tabla.setValueAt("vs", 5, 2);
        tabla.setValueAt("vs", 6, 2);
        tabla.setValueAt("vs", 7, 2);
        tabla.setValueAt("vs", 8, 2);
        
        
        tabla.setValueAt("equipo 2", 0, 3);
        tabla.setValueAt("equipo 3", 1, 3);
        tabla.setValueAt("equipo 4", 2, 3);
        tabla.setValueAt("equipo 5", 3, 3);
        tabla.setValueAt("equipo 6", 4, 3);
        tabla.setValueAt("equipo 7", 5, 3);
        tabla.setValueAt("equipo 8", 6, 3);
        tabla.setValueAt("equipo 9", 7, 3);
        tabla.setValueAt("equipo 10", 8, 3);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea_Resultado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField field_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
